version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm ci
      - npm run eslint
      - npm run test

  pre_build:
    commands:
      - echo "pre-build phase"

  build:
    commands:
      - 'SLS_DEBUG=* ./node_modules/.bin/sls deploy -v --stage dev --region us-east-2'

  post_build:
    commands:
      - echo "post build"

  