version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - sudo npm install -g serverless
      - npm install
      - npm run eslint
      - npm run test

  pre_build:
    commands:
      - echo "pre-build phase"

  build:
    commands:
      - 'SLS_DEBUG=* sls deploy -v --stage dev --region us-east-2'

  post_build:
    commands:
      - echo "post build"

  