version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo Install phase

  pre_build:
    commands:
      - echo Pre-build phase

  build:
    commands:
      - echo Build phase