# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run: pwd
      - run: ls
      - node/install-packages
      - run:
          name: Run eslint
          command: npm run eslint
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Echo done
          command: echo done!
  deploy-prod:
    docker:
      - image: cimg/node:15.1
    steps:
      - run: echo Prod deploy step
  deploy-sandbox:
    docker:
      - image: cimg/node:15.1
    steps:
      - run: echo Sandbox deploy step
  deploy-staging:
    docker:
      - image: cimg/node:15.1
    steps:
      - run: echo Staging deploy step

workflows:
  version: 2.1
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy-staging:
          requires: build-and-test
          filters:
            branches:
              only: develop
      - deploy-sandbox:
          requires: build-and-test
          filters:
            branches:
              only: sandbox
      - deploy-prod:
          requires: build-and-test
          filters:
            branches:
              only: master
