# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:  
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Run eslint
          command: eslint src/
      - run:
          name: Echo done
          command: echo done!

workflows:
  build-and-test: 
    jobs:
      - build-and-test
